version: '3.8'
services:
  db:
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testlab
      MYSQL_DATABASE: test
    volumes:
      - ./data/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

